name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Cache Go Modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-ci-${{ hashFiles('gradle.properties', 'gradle/libs.versions.toml') }}
          restore-keys:
            ${{ runner.os }}-gomod-ci-
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
        with:
          setup_only: true
          token: ${{ secrets.BUF_TOKEN }}
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      - name: Lint
        run: make lint
      - name: Generate
        run: make checkgenerate
      - name: Build
        run: make build
      - name: Docs
        run: make docs
      - name: Execute tests
        run: make test
